### ISSUE TITLE
Investigate `lodpdf` discrepancy across ilmm and open source naive ilmm

### ISSUE THREAD

**Issue by thomasgudjonwright** [invenia/LinearMixingModels.jl#16]
Currently, `logpdf` does not match to the same `atol` as all other functionality between these two models, which should be equivalent. This can be recreated and noticed by examining the `atol` provided for testing in [test/illm.jl](https://github.com/invenia/LinearMixingModels.jl/blob/master/test/ilmm.jl). Given the oilmm and ilmm are approximate up to `atol=1e-9`, this might need to be looked in to via the [naive ilmm implementation in KernelFunctions](https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/master/src/mokernels/lmm.jl).

**Comment by willtebbutt** [comment]
Did we resolve this the other day @thomasgudjonwright , or is it still a problem?

**Comment by willtebbutt** [comment]
Closed in #19
