### ISSUE TITLE
MOInputIsotopicByFeatures test failing on Julia 1.7

### ISSUE THREAD

**Issue by glennmoy** [invenia/LinearMixingModels.jl#44]
Looks like it could be just a matter of the significant digits of the values being compared by `elbo` and `logpdf` in [AbstractGPs.TestUtils.test_internal_abstractgps_interface](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/master/src/util/test_util.jl#L207)

```
MOInputIsotopicByFeatures: Test Failed at /home/runner/.julia/packages/AbstractGPs/0jusJ/src/util/test_util.jl:207
  Expression: elbo(VFE(f(z)), fx, y) <= logpdf(fx, y)
   Evaluated: -6.1470239320766975 <= -6.1470239320767
```

I'm not sure if an issue should be opened there (@willtebbutt ?) so I'll just make this one since this is where the error is. 

https://github.com/invenia/LinearMixingModels.jl/runs/4770173820?check_suite_focus=true

**Comment by willtebbutt** [comment]
Hmmm this is interesting. It definitely looks like a numerical issue to me. I'll open an issue on AbstractGPs -- I think there should be an easy fix.
